import Head from 'next/head';
import NavBar from '../components/NavBar';
import Carrossel from '../components/Carrossel';
import Cards from '@/components/Cards';
import About from '@/components/About';
import Footer from '@/components/Footer';

const images = [
  'https://via.placeholder.com/800x400?text=Slide+1',
  'https://via.placeholder.com/800x400?text=Slide+2',
  'https://via.placeholder.com/800x400?text=Slide+3',
];

export default function Home() {
  return (
      <>
        <Head>
          <title>Landing Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <div className='bg-gray-800'>
        <NavBar />
        
        <main className="container mx-auto">
          <section className="my-8-0" data-aos="fade-up">
            <Carrossel images={images} />
          </section>
          <section className="my-8" data-aos="fade-up">
            <About  />
          </section>
          <section className="my-8" data-aos="fade-up">
            <Cards />
          </section>
        </main>
        
        <Footer/>
      </div>
    </>
  );
}