import Head from 'next/head';
import NavBar from '../components/NavBar';
import Carrossel from '../components/Carrossel';

export default function Home() {
  const images = [
    'https://via.placeholder.com/800x400?text=Slide+1',
    'https://via.placeholder.com/800x400?text=Slide+2',
    'https://via.placeholder.com/800x400?text=Slide+3',
  ];

  return (
    <div>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      
      <main className="container mx-auto ">
        <Carrossel images={images} />
        <h1 className="text-4xl font-bold">Bem vindo a landing page!</h1>
        <p className="mt-4">essa landing page foi feita com Tailwind CSS e Next.js.</p>

        <section className="mt-8">
          <h2 className="text-3xl font-bold">O que é Tailwind CSS?</h2>
          <p className="mt-4">
            Tailwind CSS é um framework CSS utilitário que permite criar designs modernos e responsivos diretamente no HTML. 
            Ele fornece uma série de classes utilitárias que podem ser combinadas para construir qualquer design, sem a necessidade 
            de escrever CSS personalizado. Isso torna o desenvolvimento mais rápido e eficiente.
          </p>
        </section>
      </main>
    </div>
  );
}