import Head from 'next/head';
import NavBar from '../components/NavBar';
import Carrossel from '../components/Carrossel';
import Cards from '@/components/Cards';
import About from '@/components/About';
import Footer from '@/components/footer';


export default function Home() {
  const images = [
    'https://via.placeholder.com/800x400?text=Slide+1',
    'https://via.placeholder.com/800x400?text=Slide+2',
    'https://via.placeholder.com/800x400?text=Slide+3',
  ];

  return (
    <div className='bg-gray-800'>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <NavBar />
      
      <main className="container mx-auto">
        <section className="my-8-0">
          <Carrossel images={images} />
        </section>
        <section className="my-8">
          <About />
        </section>
        <section className="my-8">
          <Cards />
        </section>
      </main>
      
      <Footer />
    </div>
  );
}